services:
  jesus-huaripaucar-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: jesushuaripaucarcardenas/spring-api:2jun2026
    container_name: jesus-huaripaucar-api
    ports:
      - "80:80"
    restart: unless-stopped