# kubectl apply -f jesus-huaripaucar-18-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: jesus-huaripaucar-secret
  namespace: jesus-huaripaucar
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9qZXN1c2h1YXJpcGF1Y2FyOmFuZ2VsbzIwMjRAY2x1c3RlcjAuNWhvdXVsbC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==   # en Base64
  RAPIDAPI_KEY: NjIzMTQwNWEzYW1zaDVlZjNlYWQyMTA4MjFjNHAxNjg0YmNqc242ZDE5ZjQ1MjhmNGE=   # en Base64
  RAPIDAPI_CHATGPT_HOST: ZnJlZS1jaGF0Z3B0LWFwaS5wLnJhcGlkYXBpLmNvbQ==   # en Base64
  RAPIDAPI_CHATGPT_URL: aHR0cHM6Ly9mcmVlLWNoYXRncHQtYXBpLnAucmFwaWRhcGkuY29tL2NoYXQtY29tcGxldGlvbi1vbmU=   # en Base64  
  RAPIDAPI_SUMMARIZER_HOST: YXJ0aWNsZS1leHRyYWN0b3ItYW5kLXN1bW1hcml6ZXIucC5yYXBpZGFwaS5jb20=   # en Base64
  RAPIDAPI_SUMMARIZER_URL: aHR0cHM6Ly9hcnRpY2xlLWV4dHJhY3Rvci1hbmQtc3VtbWFyaXplci5wLnJhcGlkYXBpLmNvbQ==   # en Base64

# https://base64.guru/converter
# echo -n "valor" | base64
# echo "dmFsb3I=" | base64 --decode